package com.lb.sys.model;

import java.util.Date;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_ID
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_NAME
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_DESC
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.STATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATED_DATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.UPDATE_DATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.UPDATE_USER
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATED_USER
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    private String createdUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_ID
     *
     * @return the value of sys_role.ROLE_ID
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_ID
     *
     * @param roleId the value for sys_role.ROLE_ID
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_NAME
     *
     * @return the value of sys_role.ROLE_NAME
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_NAME
     *
     * @param roleName the value for sys_role.ROLE_NAME
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_DESC
     *
     * @return the value of sys_role.ROLE_DESC
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_DESC
     *
     * @param roleDesc the value for sys_role.ROLE_DESC
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.STATE
     *
     * @return the value of sys_role.STATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.STATE
     *
     * @param state the value for sys_role.STATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATED_DATE
     *
     * @return the value of sys_role.CREATED_DATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATED_DATE
     *
     * @param createdDate the value for sys_role.CREATED_DATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.UPDATE_DATE
     *
     * @return the value of sys_role.UPDATE_DATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.UPDATE_DATE
     *
     * @param updateDate the value for sys_role.UPDATE_DATE
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.UPDATE_USER
     *
     * @return the value of sys_role.UPDATE_USER
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.UPDATE_USER
     *
     * @param updateUser the value for sys_role.UPDATE_USER
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATED_USER
     *
     * @return the value of sys_role.CREATED_USER
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATED_USER
     *
     * @param createdUser the value for sys_role.CREATED_USER
     *
     * @mbg.generated Tue Sep 12 12:23:16 CST 2017
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }
}