package com.lb.sys.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserModel {
    private Long uid;  //用户编号
    private String userName;//会员名称
    private String phoneNumber;//手机号码
    private String qq;//qq
    private String weixin;//微信
    private String name;//真实姓名
    private String regIp;//注册ip地址
    private Date regTime;//注册时间
    private String usertype;//会员类型    1 NORMAL 2 PROBATION(默认为1)
    private Long score;//积分
    private Long scoreTotal;//累计积分
    private BigDecimal coin;//个人财产
    private Float fcion;//冻结资产
    private BigDecimal betsum;//投注流水
    private String email;//邮箱
    private Date updateTime;//最后修改时间
    private Date inputTime;
    private String vipName;//组别名称
    private Integer CHAT_ADMIN;
    private Long agentId;  //代理编号
    private String promotionCode; //推广代理码
    private Long parentId;//会员从属关系
    private String parents;//上级系列
    private String pssword;//密码
    private String coinPssword;//提款密码
    private Boolean source;//来源
    private String nickName;
    private Byte grade;
    private Byte status;//状态
    //组别信息
    private Integer vipId;//组别类型编号
    //最后登录ip
    private String lastloginip;//最后登录ip
    private String shangName;
    private String cid;  //个推唯一标识
    private BigDecimal withdrawNeedsum;
    private Integer rechargeTimes;
    private String bankAccount;//银行账号
    private String bankName;//取现银行名称
    private String bankAddress;//银行地址
    
    @Override
	public String toString() {
		return "UserModel [uid=" + uid + ", userName=" + userName + ", phoneNumber=" + phoneNumber + ", qq=" + qq
				+ ", weixin=" + weixin + ", name=" + name + ", regIp=" + regIp + ", regTime=" + regTime + ", usertype="
				+ usertype + ", score=" + score + ", scoreTotal=" + scoreTotal + ", coin=" + coin + ", fcion=" + fcion
				+ ", betsum=" + betsum + ", email=" + email + ", updateTime=" + updateTime + ", inputTime=" + inputTime
				+ ", vipName=" + vipName + ", CHAT_ADMIN=" + CHAT_ADMIN + ", agentId=" + agentId + ", promotionCode="
				+ promotionCode + ", parentId=" + parentId + ", parents=" + parents + ", pssword=" + pssword
				+ ", coinPssword=" + coinPssword + ", source=" + source + ", nickName=" + nickName + ", grade=" + grade
				+ ", status=" + status + ", vipId=" + vipId + ", lastloginip=" + lastloginip + ", shangName="
				+ shangName + ", cid=" + cid + ", withdrawNeedsum=" + withdrawNeedsum + ", rechargeTimes="
				+ rechargeTimes + ", bankAccount=" + bankAccount + ", bankName=" + bankName + ", bankAddress="
				+ bankAddress + "]";
	}

	public Integer getCHAT_ADMIN() {
		return CHAT_ADMIN;
	}

	public void setCHAT_ADMIN(Integer cHAT_ADMIN) {
		CHAT_ADMIN = cHAT_ADMIN;
	}

	public String getBankAccount() {
		return bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankAddress() {
		return bankAddress;
	}

	public void setBankAddress(String bankAddress) {
		this.bankAddress = bankAddress;
	}

	
	public String getCid() {
		return cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getShangName() {
		return shangName;
	}

	public void setShangName(String shangName) {
		this.shangName = shangName;
	}

	public String getLastloginip() {
		return lastloginip;
	}

	public void setLastloginip(String lastloginip) {
		this.lastloginip = lastloginip;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getVipName() {
		return vipName;
	}

	public void setVipName(String vipName) {
		this.vipName = vipName;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.INPUT_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.VIP_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UID
     *
     * @return the value of user_info.UID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UID
     *
     * @param uid the value for user_info.UID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.AGENT_ID
     *
     * @return the value of user_info.AGENT_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.AGENT_ID
     *
     * @param agentId the value for user_info.AGENT_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PROMOTION_CODE
     *
     * @return the value of user_info.PROMOTION_CODE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getPromotionCode() {
        return promotionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PROMOTION_CODE
     *
     * @param promotionCode the value for user_info.PROMOTION_CODE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setPromotionCode(String promotionCode) {
        this.promotionCode = promotionCode == null ? null : promotionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PARENT_ID
     *
     * @return the value of user_info.PARENT_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PARENT_ID
     *
     * @param parentId the value for user_info.PARENT_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PARENTS
     *
     * @return the value of user_info.PARENTS
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getParents() {
        return parents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PARENTS
     *
     * @param parents the value for user_info.PARENTS
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setParents(String parents) {
        this.parents = parents == null ? null : parents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_NAME
     *
     * @return the value of user_info.USER_NAME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_NAME
     *
     * @param userName the value for user_info.USER_NAME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PSSWORD
     *
     * @return the value of user_info.PSSWORD
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getPssword() {
        return pssword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PSSWORD
     *
     * @param pssword the value for user_info.PSSWORD
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setPssword(String pssword) {
        this.pssword = pssword == null ? null : pssword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.COIN_PSSWORD
     *
     * @return the value of user_info.COIN_PSSWORD
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getCoinPssword() {
        return coinPssword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.COIN_PSSWORD
     *
     * @param coinPssword the value for user_info.COIN_PSSWORD
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setCoinPssword(String coinPssword) {
        this.coinPssword = coinPssword == null ? null : coinPssword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PHONE_NUMBER
     *
     * @return the value of user_info.PHONE_NUMBER
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PHONE_NUMBER
     *
     * @param phoneNumber the value for user_info.PHONE_NUMBER
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.QQ
     *
     * @return the value of user_info.QQ
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.QQ
     *
     * @param qq the value for user_info.QQ
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.WEIXIN
     *
     * @return the value of user_info.WEIXIN
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.WEIXIN
     *
     * @param weixin the value for user_info.WEIXIN
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.SOURCE
     *
     * @return the value of user_info.SOURCE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Boolean getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.SOURCE
     *
     * @param source the value for user_info.SOURCE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setSource(Boolean source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.NICK_NAME
     *
     * @return the value of user_info.NICK_NAME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.NICK_NAME
     *
     * @param nickName the value for user_info.NICK_NAME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.NAME
     *
     * @return the value of user_info.NAME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.NAME
     *
     * @param name the value for user_info.NAME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.REG_IP
     *
     * @return the value of user_info.REG_IP
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.REG_IP
     *
     * @param regIp the value for user_info.REG_IP
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.REG_TIME
     *
     * @return the value of user_info.REG_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.REG_TIME
     *
     * @param regTime the value for user_info.REG_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.GRADE
     *
     * @return the value of user_info.GRADE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.GRADE
     *
     * @param grade the value for user_info.GRADE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USERTYPE
     *
     * @return the value of user_info.USERTYPE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public String getUsertype() {
    	if(this.usertype.equals(1)) {
    		return "NORMAL";
    	}else {
    		 return "PROBATION";
    	}
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USERTYPE
     *
     * @param usertype the value for user_info.USERTYPE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.SCORE
     *
     * @return the value of user_info.SCORE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.SCORE
     *
     * @param score the value for user_info.SCORE
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.SCORE_TOTAL
     *
     * @return the value of user_info.SCORE_TOTAL
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Long getScoreTotal() {
        return scoreTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.SCORE_TOTAL
     *
     * @param scoreTotal the value for user_info.SCORE_TOTAL
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setScoreTotal(Long scoreTotal) {
        this.scoreTotal = scoreTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.COIN
     *
     * @return the value of user_info.COIN
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public BigDecimal getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.COIN
     *
     * @param coin the value for user_info.COIN
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setCoin(BigDecimal coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.FCION
     *
     * @return the value of user_info.FCION
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Float getFcion() {
        return fcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.FCION
     *
     * @param fcion the value for user_info.FCION
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setFcion(Float fcion) {
        this.fcion = fcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.BETSUM
     *
     * @return the value of user_info.BETSUM
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public BigDecimal getBetsum() {
        return betsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.BETSUM
     *
     * @param betsum the value for user_info.BETSUM
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setBetsum(BigDecimal betsum) {
        this.betsum = betsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.STATUS
     *
     * @return the value of user_info.STATUS
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.STATUS
     *
     * @param status the value for user_info.STATUS
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDATE_TIME
     *
     * @return the value of user_info.UPDATE_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDATE_TIME
     *
     * @param updateTime the value for user_info.UPDATE_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.INPUT_TIME
     *
     * @return the value of user_info.INPUT_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.INPUT_TIME
     *
     * @param inputTime the value for user_info.INPUT_TIME
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.VIP_ID
     *
     * @return the value of user_info.VIP_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public Integer getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.VIP_ID
     *
     * @param vipId the value for user_info.VIP_ID
     *
     * @mbg.generated Wed Sep 20 14:11:44 CST 2017
     */
    public void setVipId(Integer vipId) {
        this.vipId = vipId;
    }

	public BigDecimal getWithdrawNeedsum() {
		return withdrawNeedsum;
	}

	public void setWithdrawNeedsum(BigDecimal withdrawNeedsum) {
		this.withdrawNeedsum = withdrawNeedsum;
	}

	public Integer getRechargeTimes() {
		return rechargeTimes;
	}

	public void setRechargeTimes(Integer rechargeTimes) {
		this.rechargeTimes = rechargeTimes;
	}

}