package com.lb.member.model;

import java.util.Date;

public class MemberDeposit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.order_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.uid
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.user_name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.recharge_amount
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Float rechargeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.apply_time
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.amount
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Float amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.coin
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Float coin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.fcoin
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Float fcoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.account_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.account
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.account_name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.operate_ip
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String operateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.operate_time
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.operate_uid
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Long operateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.operate_user
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String operateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.state
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.info
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.flag
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.pay_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.pay_type
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deposit.deposit_operate_type
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    private Byte depositOperateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.id
     *
     * @return the value of member_deposit.id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.id
     *
     * @param id the value for member_deposit.id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.order_id
     *
     * @return the value of member_deposit.order_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.order_id
     *
     * @param orderId the value for member_deposit.order_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.uid
     *
     * @return the value of member_deposit.uid
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.uid
     *
     * @param uid the value for member_deposit.uid
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.user_name
     *
     * @return the value of member_deposit.user_name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.user_name
     *
     * @param userName the value for member_deposit.user_name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.name
     *
     * @return the value of member_deposit.name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.name
     *
     * @param name the value for member_deposit.name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.recharge_amount
     *
     * @return the value of member_deposit.recharge_amount
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Float getRechargeAmount() {
        return rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.recharge_amount
     *
     * @param rechargeAmount the value for member_deposit.recharge_amount
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setRechargeAmount(Float rechargeAmount) {
        this.rechargeAmount = rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.apply_time
     *
     * @return the value of member_deposit.apply_time
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.apply_time
     *
     * @param applyTime the value for member_deposit.apply_time
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.amount
     *
     * @return the value of member_deposit.amount
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.amount
     *
     * @param amount the value for member_deposit.amount
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.coin
     *
     * @return the value of member_deposit.coin
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Float getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.coin
     *
     * @param coin the value for member_deposit.coin
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setCoin(Float coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.fcoin
     *
     * @return the value of member_deposit.fcoin
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Float getFcoin() {
        return fcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.fcoin
     *
     * @param fcoin the value for member_deposit.fcoin
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setFcoin(Float fcoin) {
        this.fcoin = fcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.account_id
     *
     * @return the value of member_deposit.account_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.account_id
     *
     * @param accountId the value for member_deposit.account_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.account
     *
     * @return the value of member_deposit.account
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.account
     *
     * @param account the value for member_deposit.account
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.account_name
     *
     * @return the value of member_deposit.account_name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.account_name
     *
     * @param accountName the value for member_deposit.account_name
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.operate_ip
     *
     * @return the value of member_deposit.operate_ip
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.operate_ip
     *
     * @param operateIp the value for member_deposit.operate_ip
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.operate_time
     *
     * @return the value of member_deposit.operate_time
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.operate_time
     *
     * @param operateTime the value for member_deposit.operate_time
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.operate_uid
     *
     * @return the value of member_deposit.operate_uid
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Long getOperateUid() {
        return operateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.operate_uid
     *
     * @param operateUid the value for member_deposit.operate_uid
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setOperateUid(Long operateUid) {
        this.operateUid = operateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.operate_user
     *
     * @return the value of member_deposit.operate_user
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getOperateUser() {
        return operateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.operate_user
     *
     * @param operateUser the value for member_deposit.operate_user
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setOperateUser(String operateUser) {
        this.operateUser = operateUser == null ? null : operateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.state
     *
     * @return the value of member_deposit.state
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.state
     *
     * @param state the value for member_deposit.state
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.info
     *
     * @return the value of member_deposit.info
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.info
     *
     * @param info the value for member_deposit.info
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.flag
     *
     * @return the value of member_deposit.flag
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.flag
     *
     * @param flag the value for member_deposit.flag
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.pay_id
     *
     * @return the value of member_deposit.pay_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.pay_id
     *
     * @param payId the value for member_deposit.pay_id
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.pay_type
     *
     * @return the value of member_deposit.pay_type
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.pay_type
     *
     * @param payType the value for member_deposit.pay_type
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deposit.deposit_operate_type
     *
     * @return the value of member_deposit.deposit_operate_type
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public Byte getDepositOperateType() {
        return depositOperateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deposit.deposit_operate_type
     *
     * @param depositOperateType the value for member_deposit.deposit_operate_type
     *
     * @mbg.generated Fri Oct 13 09:51:21 CST 2017
     */
    public void setDepositOperateType(Byte depositOperateType) {
        this.depositOperateType = depositOperateType;
    }
}