package com.lb.sys.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lb.activity.model.FriendRecommendationReward;
import com.lb.activity.model.FriendRecommendationRewardExample;

public interface FriendRecommendationRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    long countByExample(FriendRecommendationRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int deleteByExample(FriendRecommendationRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int insert(FriendRecommendationReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int insertSelective(FriendRecommendationReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    List<FriendRecommendationReward> selectByExample(FriendRecommendationRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    FriendRecommendationReward selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") FriendRecommendationReward record, @Param("example") FriendRecommendationRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int updateByExample(@Param("record") FriendRecommendationReward record, @Param("example") FriendRecommendationRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int updateByPrimaryKeySelective(FriendRecommendationReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_recommendation_reward
     *
     * @mbg.generated Mon Sep 18 17:46:27 CST 2017
     */
    int updateByPrimaryKey(FriendRecommendationReward record);

	List<Map<String, Object>> queryFriendRecommendationRewardList(Map<String, Object> map);
}