package com.lb.sys.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.lb.download.model.WithdrawRecord;
import com.lb.member.model.MemberWithdraw;
import com.lb.member.model.MemberWithdrawExample;
@Mapper
public interface MemberWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
	int manualWithDraw(Map<String,Object> map);
    long countByExample(MemberWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int deleteByExample(MemberWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int insert(MemberWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int insertSelective(MemberWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    List<MemberWithdraw> selectByExample(MemberWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    MemberWithdraw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") MemberWithdraw record, @Param("example") MemberWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByExample(@Param("record") MemberWithdraw record, @Param("example") MemberWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByPrimaryKeySelective(MemberWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_withdraw
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByPrimaryKey(MemberWithdraw record);

	List<Map<String, Object>> queryMemberWithdrawList(Map<String, Object> map);

	Map<String, Object> queryById(Map<String, Object> map);

	Map<String, Object> queryMemberWithdrawDate(Map<String, Object> hash);

	String queryStreamMultiple();

	List<WithdrawRecord> exportWithdrawRecord(Map<String, Object> map);

	Map<String, Object> withdrawQuery(Map<String, Object> map);

	Map<String, Object> withdrawUserInfo(Map<String, Object> map);
	
	int updateDrawingInfoState(Map<String, Object> map);
	
	int updateUserCoinInfo(Map<String, Object> map);
	
	int addUserCoinLog(Map<String, Object> map);
	
	int insertBetsumLog(Map<String, Object> map);
}