package com.lb.sys.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lb.download.model.DepositRecord;
import com.lb.member.model.MemberDeposit;
import com.lb.member.model.MemberDepositExample;

public interface MemberDepositMapper {
	
	int manualDeposit(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    long countByExample(MemberDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int deleteByExample(MemberDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int insert(MemberDeposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int insertSelective(MemberDeposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    List<MemberDeposit> selectByExample(MemberDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    MemberDeposit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") MemberDeposit record, @Param("example") MemberDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByExample(@Param("record") MemberDeposit record, @Param("example") MemberDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByPrimaryKeySelective(MemberDeposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deposit
     *
     * @mbg.generated Tue Sep 12 16:03:49 CST 2017
     */
    int updateByPrimaryKey(MemberDeposit record);

	List<Map<String, Object>> queryMemberDepositList(Map<String, Object> map);

	Map<String, Object> queryById(Map<String, Object> map);

	Map<String, Object> queryMemberDepositDate(Map<String, Object> hash);

	List<DepositRecord> exportDepositRecord(Map<String, Object> map);

	Map<String, Object> depositQuery(Map<String, Object> map);

	Map<String, Object> depositUserInfo(Map<String, Object> map);

	int updateDepositInfoState(Map<String, Object> map);

	int updateUserCoin(Map<String, Object> map);

	int addUserCoinLog(Map<String, Object> map);
	
	int addGiveCoinLog(Map<String, Object> memberDepositMap);

}