package com.lb.sys.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lb.activity.model.RedPacketManagement;
import com.lb.activity.model.RedPacketManagementExample;

public interface RedPacketManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    long countByExample(RedPacketManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int deleteByExample(RedPacketManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int insert(RedPacketManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int insertSelective(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    List<RedPacketManagement> selectByExample(RedPacketManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    RedPacketManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") RedPacketManagement record, @Param("example") RedPacketManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int updateByExample(@Param("record") RedPacketManagement record, @Param("example") RedPacketManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int updateByPrimaryKeySelective(RedPacketManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Thu Sep 14 15:28:30 CST 2017
     */
    int updateByPrimaryKey(RedPacketManagement record);

	List<Map<String, Object>> queryAllRedPacketManagement();

	String getVipName(List<Integer> vipIdList);
}