package com.lb.sys.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.lb.sys.model.SysMenu;
import com.lb.sys.model.SysMenuExample;
@Mapper
public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    long countByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int deleteByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    List<SysMenu> selectByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    SysMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Sep 06 11:32:09 CST 2017
     */
    int updateByPrimaryKey(SysMenu record);
  
    List<SysMenu> queryMenuListByParentId(Map<String, Object> hashMap);

	List<Map<String, Object>> getSysMenuListByRoleId(@Param("roleId")Long roleId);

	List<SysMenu> queryRoleMenuList(Map<String, Object> param);

	int selectByMenuIdRoleId(Map<String, Object> param);

	int insertRoleMenuRel(Map<String, Object> param);

	int deleteRelById(Map<String, Object> param);

	List<Map<String, Object>> queryAuthorizationMenu(Map<String, Object> map);

	int batchDelete(Map<String, Object> param);

	int batchAuthorization(Map<String, Object> param);

	List<Map<String, Object>> queryLike(Map<String, Object> map);

	List<Map<String, Object>> queryAll();

	void batchDeleteByRoleId(Map<String, Object> param);

	String queryMenuPath(@Param("roleId") Long roleId);

	int queryByMenuName(Map<String, Object> map);
	
	List<Map<String,Object>> getRealyRoleList(Map<String,Object> map);
}