package com.lb.activity.model;

import java.util.Date;

public class AppDownloadGiving {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.id
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.giving_way
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Byte givingWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.giving_credits
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Float givingCredits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.giving_proportion
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Float givingProportion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.Giving_ceiling
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Float givingCeiling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.state
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.start_time
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.end_time
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.CREATED_DATE
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.UPDATE_DATE
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.UPDATE_USER
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.CREATED_USER
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_download_giving.info
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.id
     *
     * @return the value of app_download_giving.id
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.id
     *
     * @param id the value for app_download_giving.id
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.giving_way
     *
     * @return the value of app_download_giving.giving_way
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Byte getGivingWay() {
        return givingWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.giving_way
     *
     * @param givingWay the value for app_download_giving.giving_way
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setGivingWay(Byte givingWay) {
        this.givingWay = givingWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.giving_credits
     *
     * @return the value of app_download_giving.giving_credits
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Float getGivingCredits() {
        return givingCredits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.giving_credits
     *
     * @param givingCredits the value for app_download_giving.giving_credits
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setGivingCredits(Float givingCredits) {
        this.givingCredits = givingCredits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.giving_proportion
     *
     * @return the value of app_download_giving.giving_proportion
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Float getGivingProportion() {
        return givingProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.giving_proportion
     *
     * @param givingProportion the value for app_download_giving.giving_proportion
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setGivingProportion(Float givingProportion) {
        this.givingProportion = givingProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.Giving_ceiling
     *
     * @return the value of app_download_giving.Giving_ceiling
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Float getGivingCeiling() {
        return givingCeiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.Giving_ceiling
     *
     * @param givingCeiling the value for app_download_giving.Giving_ceiling
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setGivingCeiling(Float givingCeiling) {
        this.givingCeiling = givingCeiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.state
     *
     * @return the value of app_download_giving.state
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.state
     *
     * @param state the value for app_download_giving.state
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.start_time
     *
     * @return the value of app_download_giving.start_time
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.start_time
     *
     * @param startTime the value for app_download_giving.start_time
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.end_time
     *
     * @return the value of app_download_giving.end_time
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.end_time
     *
     * @param endTime the value for app_download_giving.end_time
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.CREATED_DATE
     *
     * @return the value of app_download_giving.CREATED_DATE
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.CREATED_DATE
     *
     * @param createdDate the value for app_download_giving.CREATED_DATE
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.UPDATE_DATE
     *
     * @return the value of app_download_giving.UPDATE_DATE
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.UPDATE_DATE
     *
     * @param updateDate the value for app_download_giving.UPDATE_DATE
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.UPDATE_USER
     *
     * @return the value of app_download_giving.UPDATE_USER
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.UPDATE_USER
     *
     * @param updateUser the value for app_download_giving.UPDATE_USER
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.CREATED_USER
     *
     * @return the value of app_download_giving.CREATED_USER
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.CREATED_USER
     *
     * @param createdUser the value for app_download_giving.CREATED_USER
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_download_giving.info
     *
     * @return the value of app_download_giving.info
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_download_giving.info
     *
     * @param info the value for app_download_giving.info
     *
     * @mbg.generated Wed Oct 18 15:39:02 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}