package com.lb.activity.model;

import java.util.Date;

public class PreferentialCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.batch
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private String batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.order_number
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Integer orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.device
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private String device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.vips
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private String vips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.account
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.password
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.money
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.status
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.start_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.end_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.create_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Date createTime;
    private Date update_time;

    public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preferential_card.uid
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.batch
     *
     * @return the value of preferential_card.batch
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.batch
     *
     * @param batch the value for preferential_card.batch
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.order_number
     *
     * @return the value of preferential_card.order_number
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.order_number
     *
     * @param orderNumber the value for preferential_card.order_number
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.device
     *
     * @return the value of preferential_card.device
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.device
     *
     * @param device the value for preferential_card.device
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.vips
     *
     * @return the value of preferential_card.vips
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public String getVips() {
        return vips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.vips
     *
     * @param vips the value for preferential_card.vips
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setVips(String vips) {
        this.vips = vips == null ? null : vips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.account
     *
     * @return the value of preferential_card.account
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.account
     *
     * @param account the value for preferential_card.account
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.password
     *
     * @return the value of preferential_card.password
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.password
     *
     * @param password the value for preferential_card.password
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.money
     *
     * @return the value of preferential_card.money
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.money
     *
     * @param money the value for preferential_card.money
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.status
     *
     * @return the value of preferential_card.status
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.status
     *
     * @param status the value for preferential_card.status
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.start_time
     *
     * @return the value of preferential_card.start_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.start_time
     *
     * @param startTime the value for preferential_card.start_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.end_time
     *
     * @return the value of preferential_card.end_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.end_time
     *
     * @param endTime the value for preferential_card.end_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.create_time
     *
     * @return the value of preferential_card.create_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.create_time
     *
     * @param createTime the value for preferential_card.create_time
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preferential_card.uid
     *
     * @return the value of preferential_card.uid
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preferential_card.uid
     *
     * @param uid the value for preferential_card.uid
     *
     * @mbg.generated Wed Feb 28 14:44:00 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}