package com.lb.activity.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RedPacketManagementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public RedPacketManagementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleIsNull() {
            addCriterion("red_packet_title is null");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleIsNotNull() {
            addCriterion("red_packet_title is not null");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleEqualTo(String value) {
            addCriterion("red_packet_title =", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleNotEqualTo(String value) {
            addCriterion("red_packet_title <>", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleGreaterThan(String value) {
            addCriterion("red_packet_title >", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleGreaterThanOrEqualTo(String value) {
            addCriterion("red_packet_title >=", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleLessThan(String value) {
            addCriterion("red_packet_title <", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleLessThanOrEqualTo(String value) {
            addCriterion("red_packet_title <=", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleLike(String value) {
            addCriterion("red_packet_title like", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleNotLike(String value) {
            addCriterion("red_packet_title not like", value, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleIn(List<String> values) {
            addCriterion("red_packet_title in", values, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleNotIn(List<String> values) {
            addCriterion("red_packet_title not in", values, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleBetween(String value1, String value2) {
            addCriterion("red_packet_title between", value1, value2, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketTitleNotBetween(String value1, String value2) {
            addCriterion("red_packet_title not between", value1, value2, "redPacketTitle");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyIsNull() {
            addCriterion("red_packet_money is null");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyIsNotNull() {
            addCriterion("red_packet_money is not null");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyEqualTo(Float value) {
            addCriterion("red_packet_money =", value, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyNotEqualTo(Float value) {
            addCriterion("red_packet_money <>", value, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyGreaterThan(Float value) {
            addCriterion("red_packet_money >", value, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyGreaterThanOrEqualTo(Float value) {
            addCriterion("red_packet_money >=", value, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyLessThan(Float value) {
            addCriterion("red_packet_money <", value, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyLessThanOrEqualTo(Float value) {
            addCriterion("red_packet_money <=", value, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyIn(List<Float> values) {
            addCriterion("red_packet_money in", values, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyNotIn(List<Float> values) {
            addCriterion("red_packet_money not in", values, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyBetween(Float value1, Float value2) {
            addCriterion("red_packet_money between", value1, value2, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketMoneyNotBetween(Float value1, Float value2) {
            addCriterion("red_packet_money not between", value1, value2, "redPacketMoney");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumIsNull() {
            addCriterion("red_packet_num is null");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumIsNotNull() {
            addCriterion("red_packet_num is not null");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumEqualTo(Integer value) {
            addCriterion("red_packet_num =", value, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumNotEqualTo(Integer value) {
            addCriterion("red_packet_num <>", value, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumGreaterThan(Integer value) {
            addCriterion("red_packet_num >", value, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("red_packet_num >=", value, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumLessThan(Integer value) {
            addCriterion("red_packet_num <", value, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumLessThanOrEqualTo(Integer value) {
            addCriterion("red_packet_num <=", value, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumIn(List<Integer> values) {
            addCriterion("red_packet_num in", values, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumNotIn(List<Integer> values) {
            addCriterion("red_packet_num not in", values, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumBetween(Integer value1, Integer value2) {
            addCriterion("red_packet_num between", value1, value2, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andRedPacketNumNotBetween(Integer value1, Integer value2) {
            addCriterion("red_packet_num not between", value1, value2, "redPacketNum");
            return (Criteria) this;
        }

        public Criteria andMoneyMinIsNull() {
            addCriterion("money_min is null");
            return (Criteria) this;
        }

        public Criteria andMoneyMinIsNotNull() {
            addCriterion("money_min is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyMinEqualTo(Float value) {
            addCriterion("money_min =", value, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinNotEqualTo(Float value) {
            addCriterion("money_min <>", value, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinGreaterThan(Float value) {
            addCriterion("money_min >", value, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinGreaterThanOrEqualTo(Float value) {
            addCriterion("money_min >=", value, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinLessThan(Float value) {
            addCriterion("money_min <", value, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinLessThanOrEqualTo(Float value) {
            addCriterion("money_min <=", value, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinIn(List<Float> values) {
            addCriterion("money_min in", values, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinNotIn(List<Float> values) {
            addCriterion("money_min not in", values, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinBetween(Float value1, Float value2) {
            addCriterion("money_min between", value1, value2, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andMoneyMinNotBetween(Float value1, Float value2) {
            addCriterion("money_min not between", value1, value2, "moneyMin");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumIsNull() {
            addCriterion("limit_ip_num is null");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumIsNotNull() {
            addCriterion("limit_ip_num is not null");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumEqualTo(Integer value) {
            addCriterion("limit_ip_num =", value, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumNotEqualTo(Integer value) {
            addCriterion("limit_ip_num <>", value, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumGreaterThan(Integer value) {
            addCriterion("limit_ip_num >", value, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("limit_ip_num >=", value, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumLessThan(Integer value) {
            addCriterion("limit_ip_num <", value, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumLessThanOrEqualTo(Integer value) {
            addCriterion("limit_ip_num <=", value, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumIn(List<Integer> values) {
            addCriterion("limit_ip_num in", values, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumNotIn(List<Integer> values) {
            addCriterion("limit_ip_num not in", values, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumBetween(Integer value1, Integer value2) {
            addCriterion("limit_ip_num between", value1, value2, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andLimitIpNumNotBetween(Integer value1, Integer value2) {
            addCriterion("limit_ip_num not between", value1, value2, "limitIpNum");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleIsNull() {
            addCriterion("amount_code_multiple is null");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleIsNotNull() {
            addCriterion("amount_code_multiple is not null");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleEqualTo(Float value) {
            addCriterion("amount_code_multiple =", value, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleNotEqualTo(Float value) {
            addCriterion("amount_code_multiple <>", value, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleGreaterThan(Float value) {
            addCriterion("amount_code_multiple >", value, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleGreaterThanOrEqualTo(Float value) {
            addCriterion("amount_code_multiple >=", value, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleLessThan(Float value) {
            addCriterion("amount_code_multiple <", value, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleLessThanOrEqualTo(Float value) {
            addCriterion("amount_code_multiple <=", value, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleIn(List<Float> values) {
            addCriterion("amount_code_multiple in", values, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleNotIn(List<Float> values) {
            addCriterion("amount_code_multiple not in", values, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleBetween(Float value1, Float value2) {
            addCriterion("amount_code_multiple between", value1, value2, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andAmountCodeMultipleNotBetween(Float value1, Float value2) {
            addCriterion("amount_code_multiple not between", value1, value2, "amountCodeMultiple");
            return (Criteria) this;
        }

        public Criteria andVipIdIsNull() {
            addCriterion("vip_id is null");
            return (Criteria) this;
        }

        public Criteria andVipIdIsNotNull() {
            addCriterion("vip_id is not null");
            return (Criteria) this;
        }

        public Criteria andVipIdEqualTo(String value) {
            addCriterion("vip_id =", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotEqualTo(String value) {
            addCriterion("vip_id <>", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdGreaterThan(String value) {
            addCriterion("vip_id >", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdGreaterThanOrEqualTo(String value) {
            addCriterion("vip_id >=", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdLessThan(String value) {
            addCriterion("vip_id <", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdLessThanOrEqualTo(String value) {
            addCriterion("vip_id <=", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdLike(String value) {
            addCriterion("vip_id like", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotLike(String value) {
            addCriterion("vip_id not like", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdIn(List<String> values) {
            addCriterion("vip_id in", values, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotIn(List<String> values) {
            addCriterion("vip_id not in", values, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdBetween(String value1, String value2) {
            addCriterion("vip_id between", value1, value2, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotBetween(String value1, String value2) {
            addCriterion("vip_id not between", value1, value2, "vipId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("created_user is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("created_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(String value) {
            addCriterion("created_user =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(String value) {
            addCriterion("created_user <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(String value) {
            addCriterion("created_user >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("created_user >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(String value) {
            addCriterion("created_user <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(String value) {
            addCriterion("created_user <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLike(String value) {
            addCriterion("created_user like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotLike(String value) {
            addCriterion("created_user not like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<String> values) {
            addCriterion("created_user in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<String> values) {
            addCriterion("created_user not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(String value1, String value2) {
            addCriterion("created_user between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(String value1, String value2) {
            addCriterion("created_user not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table red_packet_management
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 13 14:35:40 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table red_packet_management
     *
     * @mbg.generated Fri Oct 13 14:35:40 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}