package com.lb.activity.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TurntablePrizeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public TurntablePrizeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPrizeContentIsNull() {
            addCriterion("prize_content is null");
            return (Criteria) this;
        }

        public Criteria andPrizeContentIsNotNull() {
            addCriterion("prize_content is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeContentEqualTo(String value) {
            addCriterion("prize_content =", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentNotEqualTo(String value) {
            addCriterion("prize_content <>", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentGreaterThan(String value) {
            addCriterion("prize_content >", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentGreaterThanOrEqualTo(String value) {
            addCriterion("prize_content >=", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentLessThan(String value) {
            addCriterion("prize_content <", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentLessThanOrEqualTo(String value) {
            addCriterion("prize_content <=", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentLike(String value) {
            addCriterion("prize_content like", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentNotLike(String value) {
            addCriterion("prize_content not like", value, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentIn(List<String> values) {
            addCriterion("prize_content in", values, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentNotIn(List<String> values) {
            addCriterion("prize_content not in", values, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentBetween(String value1, String value2) {
            addCriterion("prize_content between", value1, value2, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeContentNotBetween(String value1, String value2) {
            addCriterion("prize_content not between", value1, value2, "prizeContent");
            return (Criteria) this;
        }

        public Criteria andPrizeValueIsNull() {
            addCriterion("prize_value is null");
            return (Criteria) this;
        }

        public Criteria andPrizeValueIsNotNull() {
            addCriterion("prize_value is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeValueEqualTo(Float value) {
            addCriterion("prize_value =", value, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueNotEqualTo(Float value) {
            addCriterion("prize_value <>", value, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueGreaterThan(Float value) {
            addCriterion("prize_value >", value, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueGreaterThanOrEqualTo(Float value) {
            addCriterion("prize_value >=", value, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueLessThan(Float value) {
            addCriterion("prize_value <", value, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueLessThanOrEqualTo(Float value) {
            addCriterion("prize_value <=", value, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueIn(List<Float> values) {
            addCriterion("prize_value in", values, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueNotIn(List<Float> values) {
            addCriterion("prize_value not in", values, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueBetween(Float value1, Float value2) {
            addCriterion("prize_value between", value1, value2, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeValueNotBetween(Float value1, Float value2) {
            addCriterion("prize_value not between", value1, value2, "prizeValue");
            return (Criteria) this;
        }

        public Criteria andPrizeNumIsNull() {
            addCriterion("prize_num is null");
            return (Criteria) this;
        }

        public Criteria andPrizeNumIsNotNull() {
            addCriterion("prize_num is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeNumEqualTo(Integer value) {
            addCriterion("prize_num =", value, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumNotEqualTo(Integer value) {
            addCriterion("prize_num <>", value, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumGreaterThan(Integer value) {
            addCriterion("prize_num >", value, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_num >=", value, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumLessThan(Integer value) {
            addCriterion("prize_num <", value, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumLessThanOrEqualTo(Integer value) {
            addCriterion("prize_num <=", value, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumIn(List<Integer> values) {
            addCriterion("prize_num in", values, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumNotIn(List<Integer> values) {
            addCriterion("prize_num not in", values, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumBetween(Integer value1, Integer value2) {
            addCriterion("prize_num between", value1, value2, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeNumNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_num not between", value1, value2, "prizeNum");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightIsNull() {
            addCriterion("prize_weight is null");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightIsNotNull() {
            addCriterion("prize_weight is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightEqualTo(Integer value) {
            addCriterion("prize_weight =", value, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightNotEqualTo(Integer value) {
            addCriterion("prize_weight <>", value, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightGreaterThan(Integer value) {
            addCriterion("prize_weight >", value, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_weight >=", value, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightLessThan(Integer value) {
            addCriterion("prize_weight <", value, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightLessThanOrEqualTo(Integer value) {
            addCriterion("prize_weight <=", value, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightIn(List<Integer> values) {
            addCriterion("prize_weight in", values, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightNotIn(List<Integer> values) {
            addCriterion("prize_weight not in", values, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightBetween(Integer value1, Integer value2) {
            addCriterion("prize_weight between", value1, value2, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andPrizeWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_weight not between", value1, value2, "prizeWeight");
            return (Criteria) this;
        }

        public Criteria andTurntableIdIsNull() {
            addCriterion("turntable_id is null");
            return (Criteria) this;
        }

        public Criteria andTurntableIdIsNotNull() {
            addCriterion("turntable_id is not null");
            return (Criteria) this;
        }

        public Criteria andTurntableIdEqualTo(Integer value) {
            addCriterion("turntable_id =", value, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdNotEqualTo(Integer value) {
            addCriterion("turntable_id <>", value, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdGreaterThan(Integer value) {
            addCriterion("turntable_id >", value, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("turntable_id >=", value, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdLessThan(Integer value) {
            addCriterion("turntable_id <", value, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdLessThanOrEqualTo(Integer value) {
            addCriterion("turntable_id <=", value, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdIn(List<Integer> values) {
            addCriterion("turntable_id in", values, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdNotIn(List<Integer> values) {
            addCriterion("turntable_id not in", values, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdBetween(Integer value1, Integer value2) {
            addCriterion("turntable_id between", value1, value2, "turntableId");
            return (Criteria) this;
        }

        public Criteria andTurntableIdNotBetween(Integer value1, Integer value2) {
            addCriterion("turntable_id not between", value1, value2, "turntableId");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("created_user is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("created_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(String value) {
            addCriterion("created_user =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(String value) {
            addCriterion("created_user <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(String value) {
            addCriterion("created_user >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("created_user >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(String value) {
            addCriterion("created_user <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(String value) {
            addCriterion("created_user <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLike(String value) {
            addCriterion("created_user like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotLike(String value) {
            addCriterion("created_user not like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<String> values) {
            addCriterion("created_user in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<String> values) {
            addCriterion("created_user not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(String value1, String value2) {
            addCriterion("created_user between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(String value1, String value2) {
            addCriterion("created_user not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table turntable_prize
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 19 15:53:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table turntable_prize
     *
     * @mbg.generated Thu Oct 19 15:53:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}